package additional;

import model.Book;

import java.util.ArrayList;
import java.util.List;

public class Books {
    public static List<Book> getStartupBooks() {
        List<Book> books = new ArrayList<Book>();
        books.add(new Book("BULLSHIT JOBS: The Rise of Pointless Work, and What We Can Do About It", "David Graeber", "W 1930 roku ekonomista John Maynard Keynes przepowiedział, że do końca stulecia technologia sprawi, że będziemy pracować po piętnaście godzin tygodniowo. W książce \"Bullshit Jobs\" David Graeber bada, jak i dlaczego zamiast tego doszło do wzrostu liczby bezsensownych stanowisk pracy, które nie przynoszą społeczeństwu żadnej wartości.", 342, "41983477", "Penguin Books Ltd [UK]; Edycja 1.", true));
        books.add(new Book("The Anxious Generation: How the Great Rewiring of Childhood Is Causing an Epidemic of Mental Illness", "Jonathan Haidt", "W 1930 roku ekonomista John Maynard Keynes przepowiedział, że do końca stulecia technologia sprawi, że będziemy pracować po piętnaście godzin tygodniowo. Jednak zamiast tego stało się coś dziwnego. Obecnie średnie godziny pracy nie zmniejszyły się, lecz zwiększyły. W rozwiniętym świecie trzy czwarte wszystkich miejsc pracy to usługi lub administracja, które nie wydają się wnosić niczego wartościowego do społeczeństwa: bezsensowne prace. W książce \"Bullshit Jobs\" David Graeber bada, jak to zjawisko - kojarzone z XX-wiecznym Związkiem Radzieckim, ale które kapitalizm miał wyeliminować - stało się rzeczywistością. Analizuje, jak cenimy pracę i jak, zamiast być produktywną, stała się celem samym w sobie; jak taka praca utrzymuje obecny, wadliwy system kapitalizmu finansowego; i wreszcie, jak możemy się z tego wydostać.", 385, "241647665", "Penguin Books Ltd (UK); Edycja 1.", true));
        books.add(new Book("King of Sloth: addictive billionaire romance from the bestselling author of the Twisted series: 4", "Ana Huang", "Poznaj Królów Grzechu... Niezbędna lektura z gatunku romansów miliarderów od bestsellerowej autorki serii Twisted. 'Przygotuj się na całą pikanterię, całe napięcie i emocje' - GLAMOUR. Przeczytaj teraz \"King of Sloth\" i delektuj się gorącym romansem typu reverse grumpy sunshine. Nigdy nie chciał nikogo na tyle, by za kimś gonić... aż spotkał ją. Uroczy, wyluzowany i niewyobrażalnie bogaty, Xavier Castillo ma świat u stóp. Nie interesuje go przejęcie rodzinnego imperium (ku niezadowoleniu ojca), ale to nie powstrzymuje kobiet od rzucania się na niego... chyba że tą kobietą jest jego publicystka.", 464, "34943637", "Little, Brown Book Group; Edycja 1.", true));
        books.add(new Book("The Anxious Generation: How the Great Rewiring of Childhood Is Causing an Epidemic of Mental Illness", "Jonathan Haidt", "Od współautora bestsellerowej książki \"The Coddling of the American Mind\", \"The Anxious Generation\" to istotne śledztwo w sprawie załamania zdrowia psychicznego młodzieży i plan na zdrowsze dzieciństwo. Jonathan Haidt pokazuje, jak przeniesienie dziecięcej energii ze świata fizycznego do wirtualnego od lat 2010 miało katastrofalne skutki, zwłaszcza dla dziewcząt, oraz przedstawia kroki, które mogą podjąć rodzice, nauczyciele, szkoły i rządy, aby zakończyć epidemię chorób psychicznych i przywrócić humanitarne dzieciństwo. Haidt wyjaśnia, dlaczego media społecznościowe szkodzą dziewczętom bardziej niż chłopcom, i proponuje zasady, które mogą pomóc w rozwiązaniu tego problemu.", 400, "593655036", "Penguin Press", true));
        books.add(new Book("Co-Intelligence: Living and Working with AI", "Ethan Mollick", "„Wiedza Wspólna” to bestseller New York Timesa. „Współinteligencja” to najlepsza książka, jaką znam o aspektach, zawiłościach i etyce generatywnej sztucznej inteligencji. Porzuć wszystko i przeczytaj ją od deski do deski JUŻ – Angela Duckworth. Sztuczna inteligencja konsumencka jest faktem. Wraz z nią nadchodzi nieuchronny chaos, gdy borykamy się z tym, co oznacza to dla naszych miejsc pracy, życia i przyszłości ludzkości. Przebijając się przez szum ewangelistów i proroków zagłady AI, profesor Whartonu, Ethan Mollick, stał się jednym z najbardziej znaczących i prowokacyjnych wyjaśniaczy AI, skupiając się na praktycznych aspektach tego, w jaki sposób te nowe narzędzia myślenia mogą przekształcić nasz świat.", 236, "75356077", "Random House UK Ltd; Edycja 1.", true));
        books.add(new Book("Drama: A Graphic Novel", "Raina Telgemeier", "Od Rainy Telgemeier, autorki bestsellerów New York Timesa, laureatki wielokrotnych nagród Eisnera za \"Uśmiech\", \"Siostry\" i \"Jamy\"! Callie kocha teatr. Chociaż chętnie spróbowałaby swoich sił podczas przesłuchań do szkolnej produkcji \"Moon over Mississippi\", nie potrafi zbyt dobrze śpiewać. Zamiast tego zostaje scenografem dla grupy teatralnej, i w tym roku postanawia stworzyć scenografię godną Broadwayu przy budżecie szkoły średniej. Jednak jak to zrobić, gdy ma niewiele doświadczenia w stolarstwie, sprzedaż biletów spada, a członkowie ekipy mają trudności w pracy razem? A gdy do tego dochodzą dramaty na scenie i poza nią, gdy aktorzy zostają wybrani, sytuacja staje się jeszcze bardziej szalona! Raina Telgemeier ponownie zabiera nas w zabawną i czarującą podróż przez przyjaźń, uczucia i całą tę dramę!", 240, "338801899", "Scholastic Ltd.; Edycja 1.", true));
        books.add(new Book("It starts with us: Colleen Hoover", "Colleen Hoover", "Zanim skończyło się z nami, zaczęło się od Atasa. Colleen Hoover opowiada o ulubionym przez fanów Atasie i dzieli się tym, co przynosi dalsza część tej długo oczekiwanej kontynuacji bestsellera Sunday Timesa \"Zakończyło się z nami\".", 322, "398518174", "Simon + Schuster UK; Edycja 2.", true));
        books.add(new Book("Good Girl, Bad Blood: A Good Girl’s Guide to Murder 2", "Holly Jackson", "Bestseller New York Timesa, genialnie stworzony dreszczowiec kryminalny, to długo oczekiwana kontynuacja przeboju debiutanckiego 2019 roku. Pip Fitz-Amobi nie jest już detektywem. Wraz z pomocą Ravi Singha, opublikowała podcast o prawdziwym przypadku morderstwa, które rozwiązała z nim w zeszłym roku. Podcast stał się hitem, ale Pip twierdzi, że jej dni śledzenia są już za nią. Jednak będzie musiała złamać obietnicę, gdy znika ktoś, kogo zna. Jamie Reynolds zniknął, ale policja nie zamierza nic z tym zrobić.", 432, "40529775", "Harper Collins Publ. UK; Edycja 1.", true));
        books.add(new Book("World of Warcraft Chronicle Volume 4", "Matt Forbeck", "W czwartym tomie bestsellerowej serii World of Warcraft Chronicle nie brakuje zachwycającej sztuki i starożytnych mitów! Po katastrofalnych wydarzeniach na całym Azeroth czekają nowe przygody i stare niebezpieczeństwa dla tych, którzy są na nie gotowi. Od odkrywania zaginionych krain po demoniczną inwazję, która zmusza Hordę i Sojusz do współpracy, po podróż do samego Światów Cienia, fani nie będą chcieli przegapić tej wszechstronnej publikacji pełnej nowych spostrzeżeń fabularnych, pięknej oryginalnej sztuki, map, wykresów kosmologii, drzew rodzin postaci i wiele więcej! ", 224, "5067319", "Dark Horse Books", true));
        books.add(new Book("Case File Compendium: Bing An Ben (Novel) Vol. 1", "Rou Bao Bu Chi Rou", "Case File Compendium: Bing An Ben (Novel) Vol. 1, to zbiór opowieści kryminalnych, które przenoszą czytelnika w świat zagadek, tajemnic i zbrodni. Autor prezentuje serię fascynujących przypadków, które musi rozwiązać detektyw Bing An Ben, odkrywając zaskakujące zwroty akcji i motywy. Ta książka to gratka dla miłośników literatury kryminalnej, którzy lubią zgłębiać mroczne sekrety ludzkiej natury.", 436, "685797725", "Seven Seas; Edycja 1.", true));
        books.add(new Book("How Linux Works, 3rd Edition: What Every Superuser Should Know", "Brian Ward", "Bestsellerowy przewodnik po wewnętrznych mechanizmach systemu operacyjnego Linux, który sprzedał się w ponad 50 000 egzemplarzy od jego pierwotnego wydania w 2014 roku. Dzięki połączeniu wiedzy tła, teorii, przykładów z życia wziętych i wyczerpujących wyjaśnień, \"Jak działa Linux\", 3. edycja, nauczy Cię tego, co musisz wiedzieć, aby przejąć kontrolę nad swoim systemem operacyjnym. Praktyczne omówienie LVM, systemu dziennikowania journald i IPv6 Dodatkowy rozdział o wirtualizacji, obejmujący kontenery i cgroups.", 464, "718500408", "No Starch Press; Edycja 3rd", true));
        books.add(new Book("Bebechy, czyli ciało człowieka pod lupą", "Adam Mirek", "Twoje ciało to zagadkowa maszyna. Coś w nim stuka, huczy, kłuje. Czasem nie chce robić tego, co mu się każe (znasz to?). Dziwnie pachnie. Ma włosy w niektórych miejscach, a w innych jest zupełnie łyse.Chodź, zajrzymy do wnętrza twojego organizmu. Uroczyście przysięgam: nie cofniemy się przed niczym, żadna (nawet najbardziej obleśna!) tajemnica ludzkiego ciała nas nie powstrzyma. Wślizgniemy się z lupą w sam środek twoich bebechów.Dowiesz się: dlaczego twój oddech pachnie czasami jak oddech zombiaka,kiedy twój mózg przypomina rollercoaster,jak to się dzieje, że nawet najpyszniejsze lody zamieniają się w… no wiesz, w co,dlaczego męczysz się nad nauką, ale nie wtedy, kiedy oglądasz seriale. Adam Mirek – trochę szalony i supermądry naukowiec. Młodzi kochają go za to, jak opowiada o nauce w mediach społecznościowych, a dorośli pewnie bardziej docenią fakt, że zrobił doktorat na dwóch uczelniach.", 272, "832409315X", "Znak Emotikon; Pierwsza edycja", true));
        books.add(new Book("BOGATY OJCIEC BIEDNY OJCIEC WYD. JUBILEUSZOWE: czego bogaci uczą swoje dzieci na temat pieniędzy i o czym nie wiedzą biedni i klasa średnia", "Robert T. Kiyosaki", "Czego bogaci uczą swoje dzieci na temat pieniędzy i o czym nie wiedzą biedni i średnia klasa? Dowiedz się, jak sprawić, aby pieniądze pracowały dla ciebie i dlaczego nie musisz mieć bardzo wysokiej pensji, aby stać się zamożnym. Książka, która wstrząsnęła światem finansów! \"Bogaty ojciec, Biedny ojciec\" - czyli czego bogaci uczą swoje dzieci na temat pieniędzy i o czym nie wiedzą biedni i średnia klasa - od kilku lat utrzymuje się na szczycie światowych bestsellerów biznesu. Autor, Robert Kiyosaki, otwiera nam oczy na świat, jakiego nie poznamy w szkole czy na studiach. Na początku wydaje się nieco kontrowersyjna, ale im dłużej ją czytasz, tym bardziej uświadamiasz sobie swoją niewiedzę i potrzebę dokonania zmian w swoim życiu. Dowiesz się jak umiejętnie generować i pomnażać swoje pieniądze.", 344, "8361008403", "Instytut Praktycznej Edukacji", true));
        books.add(new Book("PARTNERSTWO BLISKOŚCI: Jak teoria więzi pomoże ci stworzyć szczęśliwy związek", "Levine Amir", "Ta książka jest przewodnikiem dla par, które pragną budować zdrowe i trwałe relacje. Opiera się na teorii więzi, która zajmuje się dynamiką relacji międzyludzkich i sposobami budowania więzi emocjonalnej. Zawiera praktyczne wskazówki, ćwiczenia i studia przypadków, które pomagają czytelnikom lepiej zrozumieć i wzmocnić swoje związki.", 328, "8366380408", "Feeria", true));
        books.add(new Book("JAK PRZESTAĆ SIĘ MARTWIĆ I ZACZĄĆ ŻYĆ", "Carnegie Dale", "Dzięki książce Jak przestać się martwić i zacząć żyć, miliony ludzi pozbyło się kłopotów, które zatruwały im życie. Niektórzy z nich dzielą się swymi doświadczeniami z czytelnikiem. Ta publikacja jest panaceum na obawy i lęki, udowadnia, że życie człowieka nie musi być pełne niepokoju i napięć, pozbawiających szczęścia i odbierających siły.", 392, "8367107004", "Studio Emka; Edycja 2.", true));
        books.add(new Book("JAK ZDOBYĆ PRZYJACIÓŁ I ZJEDNAĆ SOBIE... wyd. 2022", "Carnegie Dale", "Sekretem sukcesu tej książki jest jej prostota. A jak wiadomo najtrudniej pisać najprościej. Każda rada w niej zawarta wydaje się oczywista. Człowiecza mądrość tkwi w podświadomości. Sztuką jest jej wydobycie i zastosowanie w działaniu. Niewielu to potrafi. Carnegie tak. Po mistrzowsku. Jak zdobyć przyjaciół i zjednać sobie ludzi ułatwia swobodne poruszanie się w biznesie. Przydaje się znakomicie w życiu rodzinnym i towarzyskim.", 312, "836710702", "Studio Emka; Edycja 2.", true));
        books.add(new Book("GLUKOZOWA REWOLUCJA: Kontroluj poziom cukru we krwi, odzyskaj energię i jedz to, na co masz ochotę", "Inchauspe Jessie", "\"GLUKOZOWA REWOLUCJA\" to przewodnik, który pomoże ci zrozumieć, jak kontrolować poziom cukru we krwi, abyś mógł cieszyć się lepszym zdrowiem i większą energią. Autorzy przedstawiają praktyczne porady dotyczące diety, aktywności fizycznej i stylu życia, które pomogą ci utrzymać stabilny poziom glukozy we krwi, uniknąć skoków cukru i spadków energii oraz poprawić ogólny stan zdrowia. Ta książka to nie tylko poradnik żywieniowy, ale również inspirujące źródło motywacji i wiedzy, które pomoże ci lepiej zrozumieć, jak wpływać na swoje zdrowie poprzez świadome wybory żywieniowe i styl życia.", 320, "8367674308", "Marginesy; Edycja 1.", true));
        books.add(new Book("ATOMOWE NAWYKI dodruk 2023: Drobne zmiany, niezwykłe efekty", "Clear James", "Atomowe nawyki to sprawdzona i poparta naukowymi dowodami metoda kształtowania dobrych przyzwyczajeń i wyzbywania się złych nawyków. Fundamentem książki jest model nawyków składający się z czterech kroków (wskazówki, pragnienia, reakcji i nagrody) oraz czterech praw zmiany zachowania, które z tych kroków wynikają. Przedstawione przez autora założenia stanowią zintegrowany model bazujący na naukach kognitywnych i behawioralnych. Jego zdaniem jest to jeden z pierwszych modeli ludzkiego zachowania, który uwzględnia wpływ na nawyki zarówno bodźców zewnętrznych, jak i wewnętrznych emocji. Choć niektóre terminy mogą być znane, niektóre szczegóły – oraz zastosowanie czterech praw zmiany zachowania – wskażą czytelnikom nowe podejście do nawyków.", 284, "8375797383", "Galaktyka", true));
        books.add(new Book("CZŁOWIEK W POSZUKIWANIU SENSU", "Frankl Viktor E.", "Człowiek w poszukiwaniu sensu Viktora E. Frankla to jedna z najbardziej wpływowych książek w literaturze psychiatrycznej od czasu Freuda. Zaczyna się od długiego, suchego i głęboko poruszającego osobistego eseju o pięcioletnim pobycie Frankla w Auschwitz i innych obozach koncentracyjnych i jego wysiłkach w tym czasie, by znaleźć powody do życia. Druga część książki opisuje metody psychoterapeutyczne, które Frankl opracował jako pierwszy na bazie swoich doświadczeń z obozów. Freud uważał, że życiem człowieka rządzi popęd seksualny i pokusy. Frankl z kolei wierzy, że najgłębszym popędem człowieka jest poszukiwanie sensu i celu. Logoterapia Frankla zatem bardziej przystaje do zachodnich religii niż freudeowskiej psychoterapii.", 224, "83825265", "Czarna Owca; Edycja 3.", true));
        books.add(new Book("Kiedy ciało mówi nie. Koszty ukrytego stresu", "Gabor Maté", "Czy można dosłownie umrzeć z samotności? Czy istnieje połączenie między zdolnością wyrażania emocji a chorobą Alzheimera? Czy można zdefiniować „osobowość nowotworową”? Przedstawia dowody naukowe na to, jaką rolę odgrywają stres i emocje w występowaniu szeregu powszechnych chorób takich jak zapalenie stawów, nowotwory, cukrzyca, choroby serca, zespół jelita drażliwego czy stwardnienie rozsiane. Na podstawie dziesiątek studiów przypadków i historii takich osób jak Ronald Reagan (alzheimer) czy Lance Armstrong (rak jąder) Gabor Maté ujawnia Siedem zasad zdrowienia, czyli reguł pomagających uchronić się przed ukrytym stresem.Kiedy ciało mówi nie to międzynarodowy bestseller przetłumaczony na piętnaście języków, propagujący uczenie się i leczenie poprzez dostarczanie transformującego wglądu w to, w jaki sposób choroba może być sposobem na odrzucenie przez organizm tego, czego umysł nie może lub nie chce uznać.", 352, "8382529119", "Czarna Owca; Edycja 1.", true));
        books.add(new Book("Harry Potter i Zakon Feniksa (wydanie ilustrowane)", "J.K. Rowling", "Już po raz piąty postacie z serii o Harrym Potterze ożywają na kartach książki za sprawą fenomenalnych ilustracji Jima Kaya. Tym razem artyście towarzyszy Neil Packer, niezwykle uzdolniony twórca, którego prace zasiliły piąty tom.Harry’ego czeka kolejny rok nauki w Hogwarcie i chciałby jak najszybciej spotkać się ze swoimi najlepszymi przyjaciółmi, Ronem i Hermioną. Wygląda jednak na to, że nowy rok nauki będzie obfitował w wiele dramatycznych wydarzeń. Lord Voldemort powrócił i cały czarodziejski świat musi to przyjąć do wiadomości.", 568, "8382651836", "Media Rodzina", true));

        return books;
    }
}
